# config.yaml

api:
  #endpoint: "http://localhost:11434/api/generate"  # Default Ollama API endpoint
  endpoint: "http://localhost:11434/api/chat"  # Default Ollama API endpoint
  # Add authentication if required
  # headers:
  #   Authorization: "Bearer YOUR_API_KEY"

model:
  name: "granite3-moe:3b"  # Default model name
  temperature: 0
  max_tokens: 150

files:
  input_csv: "input.csv"
  output_csv: "output.csv"
  log_file: "app.log"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
